version: "3.8"

services:
  certbot:
    image: certbot/certbot
    entrypoint:  >
      /bin/sh -c "trap exit TERM; while :; do
      certbot certonly --standalone --preferred-challenges http --agree-tos;
      certbot renew; sleep 12h & wait $${!}; done;"
    environment:
      - CERTBOT_EMAIL=<YOUR_EMAIL>
      - CERTBOT_DOMAIN=<YOUR_DOMAIN_HERE>
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  proxy:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
     - ./ngix/conf.d:/etc/nginx/conf.d
     - ./ngix/nginx.conf:/etc/nginx/nginx.conf
     - ./ngix/log:/var/log/nginx
     - ./certbot/conf:/etc/letsencrypt
    ports:
     - "443:443"
     - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"