version: '3.8'

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  bsc-execution:
    <<: *logging
    image: ghcr.io/node-real/bsc-erigon:1.2.8
    container_name: bsc-execution
    restart: unless-stopped
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
#    deploy:
#      resources:
#        limits:
#          cpus: '16'
#          memory: 56G
#    mem_swappiness: 0
    command:
      - --chain=bsc
      - --datadir=/root/.local/share/erigon
      - --port=30303
      - --private.api.addr=0.0.0.0:9090
      - --torrent.port=42069
      - --torrent.download.rate=1000mb
      - --torrent.download.slots=6
      - --p2p.protocol=66,67
      - --sentry.drop-useless-peers=true
      - --nat=extip:<host IP> # Replace with host IP address
      - --maxpeers=250
      - --downloader.verify
      - --etl.bufferSize=512M
      - --db.pagesize=16k
      - --db.size.limit=12TB
      - --healthcheck
      - --log.console.verbosity=info
      - --bodies.cache=214748364800
      - --batchSize=4096M
      - --sentry.drop-useless-peers
    volumes:
      - ./erigon:/root/.local/share/erigon
    expose:
      - 9090
    ports:
      # P2P TCP (Default: 30303)
      - 30303:30303/tcp
      # P2P UDP (Default: 30303)
      - 30303:30303/udp
      # BitTorrent TCP (Default: 42069)
      - 42069:42069/tcp
      # BitTorrent UDP (Default: 42069)
      - 42069:42069/udp

  bsc-rpcdaemon:
    <<: *logging
    image: ghcr.io/node-real/bsc-erigon:1.1.9
    container_name: bsc-rpcdaemon
    restart: unless-stopped
    user: root
    pid: service:bsc-execution
#    deploy:
#      resources:
#        limits:
#          cpus: '16'
#          memory: 16G
#    mem_swappiness: 0
    entrypoint: rpcdaemon
    command:
      - --datadir=/root/.local/share/erigon
      - --http.port=8550
      - --ws
      - --http.api=eth,debug,net,trace,web3
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --private.api.addr=bsc-execution:9090
      - --db.read.concurrency=512
      - --rpc.batch.concurrency=32
    depends_on:
      - bsc-execution
    volumes_from:
      - bsc-execution
    ports:
      # RPC TCP (Default: 8545)
      - 8545:8545