version: '3.8'

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  bsc-execution:
    <<: *logging
    image: ghcr.io/node-real/bsc-erigon:1.2.10
    container_name: bsc-execution
    restart: unless-stopped
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
#    deploy:
#      resources:
#        limits:
#          cpus: '16'
#          memory: 32G
#    mem_swappiness: 0
    command:
      - --chain=bsc
      - --datadir=/home/erigon/.local/share/erigon
      - --port=30305
      - --nat=extip:<YOUR_EXTERNAL_IP> # Replace <YOUR_EXTERNAL_IP> with your actual external IP address
      - --private.api.addr=0.0.0.0:9090
      - --maxpeers=250
      - --torrent.port=42070
      - --torrent.download.rate=1000mb
      - --torrent.download.slots=6
      - --p2p.protocol=68
      - --downloader.verify
      - --db.size.limit=12TB
      - --db.pagesize=16k
      - --healthcheck
      - --txpool.disable
      - --bodies.cache=214748364800
      - --batchSize=4096M
      - --etl.bufferSize=512M
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6061
      - --log.console.verbosity=info
    volumes:
      - ./erigon:/home/erigon/.local/share/erigon
    expose:
      - 8551
      - 9090
    ports:
      # P2P TCP (Default: 30303)
      - 30305:30305/tcp
      # P2P UDP (Default: 30303)
      - 30305:30305/udp
      # BitTorrent TCP (Default: 42069)
      - 42070:42070/tcp
      # BitTorrent UDP (Default: 42069)
      - 42070:42070/udp
      # Expose port to bind on localhost only,
      # preventing access from the general Internet
      # Prometheus TCP (Default: 6060)
      - 127.0.0.1:6061:6061
    networks:
      - nda-management-network

  bsc-rpcdaemon:
    <<: *logging
    image: ghcr.io/node-real/bsc-erigon:1.2.10
    container_name: bsc-rpcdaemon
    restart: unless-stopped
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    pid: service:bsc-execution
#    deploy:
#      resources:
#        limits:
#          cpus: '16'
#          memory: 16G
#    mem_swappiness: 0
    entrypoint: rpcdaemon
    command:
      - --datadir=/home/erigon/.local/share/erigon
      - --http.port=8550
      - --ws
      - --http.api=eth,debug,net,trace,web3,txpool,admin
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --private.api.addr=bsc-execution:9090
      - --db.read.concurrency=512
      - --rpc.batch.concurrency=32
    depends_on:
      - bsc-execution
    volumes_from:
      - bsc-execution
    ports:
      # Expose port to bind on localhost only,
      # preventing access from the general Internet
      # JSON RPC TCP (Default: 8545)
      - 127.0.0.1:8550:8550
    networks:
      - nda-management-network

networks:
  nda-management-network:
    external: true