version: '3.8'

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  rabbitmq:
    <<: *logging
    image: rabbitmq:3-alpine
    container_name: matic-rabbitmq
    restart: unless-stopped
    expose:
      - 5672
    networks:
      - nda-management-network

  heimdall:
    <<: *logging
    image: 0xpolygon/heimdall:latest
    container_name: matic-heimdall
    restart: unless-stopped
    depends_on:
      - rabbitmq
    command:
      - start
      - --chain=mainnet
      - --home=/heimdall-home
      - --p2p.laddr=tcp://0.0.0.0:26666
      - --rpc.laddr=tcp://0.0.0.0:26667
      - --eth_rpc_url=https://eth-mainnet.rpc.grove.city/v1/YOUR_APPLICATION_ID # Replace YOUR_APPLICATION_ID with your actual Grove APP ID
      - --bor_rpc_url=http://bor-rpcdaemon:8560
      - --amqp_url=amqp://guest:guest@rabbitmq:5672/
      - --rest-server
    volumes:
      - ./heimdall:/heimdall-home
    ports:
      # P2P TCP (Default: 26656)
      - 26666:26666
      # Expose ports to bind on localhost only,
      # preventing access from the general Internet
      # RPC TCP (Default: 26657)
      - 127.0.0.1:26667:26667
      # Heimdall REST API
      - 127.0.0.1:1317:1317
    networks:
      - nda-management-network

  bor:
    <<: *logging
    image: thorax/erigon:v2.60.1
    container_name: matic-bor
    restart: unless-stopped
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
#    deploy:
#      resources:
#        limits:
#          cpus: '16'
#          memory: 32G
#    mem_swappiness: 0
    command:
      - --chain=bor-mainnet
      - --datadir=/home/erigon/.local/share/erigon
      - --port=30307
      - --bor.heimdall=http://heimdall:1317
      - --bor.milestone
      - --rpc.returndata.limit=300000
      - --nat=extip:<YOUR_EXTERNAL_IP> # Replace <YOUR_EXTERNAL_IP> with your actual external IP address
      - --private.api.addr=0.0.0.0:9090
      - --maxpeers=300
      - --torrent.port=42072
      - --torrent.download.rate=1000mb
      - --torrent.download.slots=10
      - --torrent.verbosity=3
      - --downloader.verify
      - --db.pagesize=16k
      - --db.size.limit=16TB
      - --batchSize=512M
      - --etl.bufferSize=512M
      - --p2p.allowed-ports=30308,30309,30310
      - --p2p.protocol=66,67
      - --bootnodes=enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303,enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6063
      - --log.console.verbosity=info
    volumes:
      - ./bor:/home/erigon/.local/share/erigon
    expose:
      - 9090
    ports:
      # P2P TCP (Default: 30303)
      - 30307:30307/tcp
      # P2P UDP (Default: 30303)
      - 30307:30307/udp
      # BitTorrent TCP (Default: 42069)
      - 42072:42072/tcp
      # BitTorrent UDP (Default: 42069)
      - 42072:42072/udp
      # Additional P2P Allowed Ports
      - 30308-30310:30308-30310
      # Expose port to bind on localhost only,
      # preventing access from the general Internet
      # Prometheus TCP (Default: 6060)
      - 127.0.0.1:6063:6063
    networks:
      - nda-management-network

  bor-rpcdaemon:
    <<: *logging
    image: thorax/erigon:v2.60.1
    container_name: matic-rpcdaemon
    restart: unless-stopped
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    pid: service:bor
#    deploy:
#      resources:
#        limits:
#          cpus: '4'
#          memory: 8G
#    mem_swappiness: 0
    entrypoint: rpcdaemon
    command:
      - --datadir=/home/erigon/.local/share/erigon
      - --http.port=8560
      - --ws
      - --http.api=eth,erigon,web3,net,debug,trace,txpool
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --private.api.addr=bor:9090
      - --db.read.concurrency=512
      - --rpc.batch.concurrency=32
    depends_on:
      - bor
    volumes_from:
      - bor
    ports:
      # Expose ports to bind on localhost only,
      # preventing access from the general Internet
      # JSON RPC TCP (Default: 8545)
      - 127.0.0.1:8560:8560
    networks:
      - nda-management-network

networks:
  nda-management-network:
    external: true