version: "3.8"

services:
  pocket-mesh:
    image: poktscan/pocket-core:MESH-RC-0.5.1-RC-0.12.0
    container_name: pocket-mesh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["pocket", "start-mesh", "--datadir=/home/app/.pocket"]
    volumes:
      - "./mesh/.pocket:/home/app/.pocket"
    ports:
      # Expose ports to bind on localhost,
      # but not for general Internet
      # Pocket JSON-RPC (Default: 8081)
      - "127.0.0.1:8082:8082"
      # Prometheus TCP (Default: 8083)
      - "127.0.0.1:8084:8084"
    networks:
      - nda-management-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

networks:
  nda-management-network:
    external: true
