version: "3.8"

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  pocket-node:
    <<: *logging
    image: poktscan/pocket-core:BETA-MESH-RC-0.5.0-RC-0.11.1
    container_name: pocket-node
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["pocket", "start", "--mainnet", "--datadir=/home/app/.pocket", "--keybase=false"]
    volumes:
      - "./node/.pocket/:/home/app/.pocket/"
    ports:
      # Pocket JSON-RPC
      - "8081:8081"
      # Prometheus Metrics  
      - "8083:8083"
      # Tendermint P2P   
      - "26656:26656"
      # Tendermint JSON-RPC
      - "26657:26657"
  pocket-mesh:
    <<: *logging
    image: poktscan/pocket-core:MESH-RC-0.4.2-RC-0.11.1
    container_name: pocket-mesh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["pocket", "start-mesh", "--datadir=/home/app/.pocket"]
    depends_on:
      - pocket-node
    volumes:
      - "./mesh/.pocket:/home/app/.pocket"
    ports:
      # Pocket JSON-RPC (Default: 8081)
      - "8082:8082"
  prometheus:
    <<: *logging
    image: prom/prometheus:v2.51.2
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000} # Uses erigon user from Dockerfile
    command: --log.level=warn --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=150d --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    ports:
      - "9090:9090"
    volumes:
      - ${POKT_PROMETHEUS_CONFIG:-./prometheus/prometheus.yml}:/etc/prometheus/prometheus.yml
      - ${XDG_DATA_HOME:-~/.local/share}/pokt-prometheus:/prometheus
    restart: unless-stopped
  grafana:
    <<: *logging
    image: grafana/grafana:10.4.2
    user: "472:0" # required for grafana version >= 7.3
    ports:
      - "3000:3000"
    volumes:
      - ${POKT_GRAFANA_CONFIG:-./prometheus/grafana.ini}:/etc/grafana/grafana.ini
      - ./prometheus/datasources:/etc/grafana/provisioning/datasources
      - ./prometheus/dashboards:/etc/grafana/provisioning/dashboards
      - ${XDG_DATA_HOME:-~/.local/share}/pokt-grafana:/var/lib/grafana
    restart: unless-stopped

