version: "3.8"

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  pocket-node:
    <<: *logging
    image: poktscan/pocket-core:MESH-RC-0.5.1-RC-0.12.0
    container_name: pocket-node
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["pocket", "start", "--mainnet", "--datadir=/home/app/.pocket", "--keybase=false"]
    volumes:
      - "./node/.pocket/:/home/app/.pocket/"
    ports:
      # Tendermint P2P   
      - "0.0.0.0:26656:26656"
      # Tendermint JSON-RPC
      - "0.0.0.0:26657:26657"
      # Expose ports to bind on localhost,
      # but not for general Internet
      # Pocket JSON-RPC
      - "127.0.0.1:8081:8081"
      # Prometheus Metrics  
      - "127.0.0.1:8083:8083"
      - "127.0.0.1:26660:26660"
    networks:
      - nda-management-network
  pocket-mesh:
    <<: *logging
    image: poktscan/pocket-core:MESH-RC-0.5.1-RC-0.12.0
    container_name: pocket-mesh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["pocket", "start-mesh", "--datadir=/home/app/.pocket"]
    depends_on:
      - pocket-node
    volumes:
      - "./mesh/.pocket:/home/app/.pocket"
    ports:
      # Expose ports to bind on localhost,
      # but not for general Internet
      # Pocket JSON-RPC (Default: 8081)
      - "127.0.0.1:8082:8082"
      # Prometheus Metrics  
      - "127.0.0.1:8084:8084"
    networks:
      - nda-management-network

networks:
  nda-management-network:
    external: true
