version: "3.8"

services:
  pocket-node:
    image: poktscan/pocket-core:MESH-RC-0.5.1-RC-0.12.0
    container_name: pocket-node
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - POCKET_CORE_PASSPHRASE=${POCKET_CORE_PASSPHRASE}
      - POCKET_CORE_KEY=${POCKET_CORE_KEY}
      - POCKET_CORE_ADDRESS=${POCKET_CORE_ADDRESS}
    command: ["pocket", "start", "--mainnet",  "--datadir=/home/app/.pocket"]
    volumes:
      - "./node/.pocket/:/home/app/.pocket/"
    ports:
      # Tendermint P2P   
      - "0.0.0.0:26656:26656"
      # Tendermint JSON-RPC
      - "0.0.0.0:26657:26657"
      # Expose ports to bind on localhost,
      # but not for general Internet
      # Pocket JSON-RPC
      - "127.0.0.1:8081:8081"
      # Prometheus Metrics
      - "127.0.0.1:8083:8083"
      - "127.0.0.1:26660:26660"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    networks:
      - nda-management-network

networks:
  nda-management-network:
    external: true
