version: '3.8'

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  eth-execution:
    <<: *logging
    image: thorax/erigon:v2.60.1
    container_name: eth-execution
    restart: unless-stopped
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
#    deploy:
#      resources:
#        limits:
#          cpus: '8'
#          memory: 16G
#    mem_swappiness: 0
    command:
      - --datadir=/home/erigon/.local/share/erigon
      - --port=30303
      - --prune=htc
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --nat=extip:<HOST IP> # Replace with host IP address
      - --private.api.addr=0.0.0.0:9090
      - --maxpeers=200
      - --torrent.port=42069
      - --torrent.download.rate=1000mb
      - --torrent.download.slots=6
      - --downloader.verify
      - --db.size.limit=2TB
      - --batchSize=512M
      - --etl.bufferSize=512M
      - --metrics 
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      - --log.console.verbosity=info
    volumes:
      - ./erigon:/home/erigon/.local/share/erigon
    expose:
      - 8551
      - 9090
      - 6060
    ports:
      # P2P TCP (Default: 30303)
      - 30303:30303/tcp
      # P2P UDP (Default: 30303)
      - 30303:30303/udp
      # BitTorrent TCP (Default: 42069)
      - 42069:42069/tcp
      # BitTorrent UDP (Default: 42069)
      - 42069:42069/udp

  eth-rpcdaemon:
    <<: *logging
    image: thorax/erigon:v2.60.1
    container_name: eth-rpcdaemon
    restart: unless-stopped
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    pid: service:eth-execution
#    deploy:
#      resources:
#        limits:
#          cpus: '4'
#          memory: 8G
#    mem_swappiness: 0
    entrypoint: rpcdaemon
    command:
      - --datadir=/home/erigon/.local/share/erigon
      - --http.port=8545
      - --ws
      - --http.api=eth,debug,net,trace,web3
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --private.api.addr=eth-execution:9090
      - --db.read.concurrency=512
      - --rpc.batch.concurrency=32
    depends_on:
      - eth-execution
    volumes_from:
      - eth-execution
    ports:
      # RPC TCP (Default: 8545)
      # Expose RPC port to bind on localhost,
      # but not for general Internet
      - 127.0.0.1:8545:8545

  eth-consensus:
    <<: *logging
    image: sigp/lighthouse:latest
    container_name: eth-consensus
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '8'
#          memory: 24G
    command:
      - lighthouse
      - beacon_node
      - --network=mainnet
      - --datadir=/root/.lighthouse
      - --debug-level=info
      - --port=9000
      - --eth1
      - --http
      - --http-address=0.0.0.0
      - --http-port=5052
      - --http-allow-origin=*
      - --execution-jwt=/jwt.hex
      - --execution-endpoint=http://eth-execution:8551
      - --checkpoint-sync-url=https://beaconstate.info
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-port=5054
      - --disable-upnp
    depends_on:
      - eth-execution
    volumes:
      - ./lighthouse:/root/.lighthouse
      - ./erigon/jwt.hex:/jwt.hex
    expose:
      - 5054
    ports:
      # P2P TCP (Default: 9000)
      - 9000:9000/tcp
      # P2P UDP (Default: 9000)
      - 9000:9000/udp
      # Expose API port to bind on localhost,
      # but not for general Internet
      - 127.0.0.1:5052:5052