version: '3.8'

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  gnosis-execution:
    <<: *logging
    image: thorax/erigon:2.60.7
    container_name: gnosis-execution
    restart: unless-stopped
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
#    deploy:
#      resources:
#        limits:
#          cpus: '16'
#          memory: 32G
#    mem_swappiness: 0
    command:
      - --datadir=/home/erigon/.local/share/erigon
      - --port=30306
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --nat=extip:<YOUR_EXTERNAL_IP> # Replace <YOUR_EXTERNAL_IP> with your actual external IP address
      - --private.api.addr=0.0.0.0:9090
      - --maxpeers=200
      - --torrent.port=42071
      - --torrent.download.rate=1000mb
      - --torrent.download.slots=6
      - --downloader.verify
      - --db.size.limit=3TB
      - --batchSize=512M
      - --etl.bufferSize=512M
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6062
      - --log.console.verbosity=info
    volumes:
      - ./erigon:/home/erigon/.local/share/erigon
    expose:
      - 8551
      - 9090
    ports:
      # P2P TCP (Default: 30303)
      - 30306:30306/tcp
      # P2P UDP (Default: 30303)
      - 30306:30306/udp
      # BitTorrent TCP (Default: 42069)
      - 42071:42071/tcp
      # BitTorrent UDP (Default: 42069)
      - 42071:42071/udp
      # Expose port to bind on localhost only,
      # preventing access from the general Internet
      # Prometheus TCP (Default: 6060)
      - 127.0.0.1:6062:6062
    networks:
      - nda-management-network

  gnosis-rpcdaemon:
    <<: *logging
    image: thorax/erigon:2.60.7
    container_name: gnosis-rpcdaemon
    restart: unless-stopped
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    pid: service:gnosis-execution
#    deploy:
#      resources:
#        limits:
#          cpus: '4'
#          memory: 8G
#    mem_swappiness: 0
    entrypoint: rpcdaemon
    command:
      - --datadir=/home/erigon/.local/share/erigon
      - --http.port=8555
      - --ws
      - --http.api=eth,debug,net,trace,web3
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --private.api.addr=gnosis-execution:9090
      - --db.read.concurrency=512
      - --rpc.batch.concurrency=32
    depends_on:
      - gnosis-execution
    volumes_from:
      - gnosis-execution
    ports:
      # Expose port to bind on localhost only,
      # preventing access from the general Internet
      # JSON RPC TCP (Default: 8545)
      - 127.0.0.1:8555:8555
    networks:
      - nda-management-network

  gnosis-consensus:
    <<: *logging
    image: sigp/lighthouse:latest
    container_name: gnosis-consensus
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '6'
#          memory: 16G
    command:
      - lighthouse
      - beacon_node
      - --network=gnosis
      - --datadir=/root/.lighthouse
      - --debug-level=info
      - --port=9000
      - --eth1
      - --http
      - --http-address=0.0.0.0
      - --http-port=5053
      - --http-allow-origin=*
      - --discovery-port=9010
      - --execution-jwt=/jwt.hex
      - --execution-endpoint=http://gnosis-execution:8551
      - --checkpoint-sync-url=https://checkpoint.gnosischain.com
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-port=5055
      - --disable-upnp
      - --prune-blobs=false
    depends_on:
      - gnosis-execution
    volumes:
      - ./lighthouse:/root/.lighthouse
      - ./erigon/jwt.hex:/jwt.hex
    ports:
      # P2P TCP (Default: 9000)
      - 9010:9010/tcp
      # P2P UDP (Default: 9000)
      - 9010:9010/udp
      # Expose ports to bind on localhost only,
      # preventing access from the general Internet
      # JSON RPC TCP (Default: 5052)
      - 127.0.0.1:5053:5053
      # Prometheus TCP (Default: 5054)
      - 127.0.0.1:5055:5055
    networks:
      - nda-management-network

networks:
  nda-management-network:
    external: true
